version: "3.0"

services:
  app:
    image: "cloudova/service"
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    entrypoint: "java -jar /app/cloudova.jar"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/cloudova"
      SPRING_DATASOURCE_USERNAME: "cloudova"
      SPRING_DATASOURCE_PASSWORD: "example"
      SPRING_DATASOURCE_driverClassName: "com.mysql.cj.jdbc.Driver"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: cloudova
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cloudova

volumes:
  db: {}