version: "3.0"

services:
#  app:
#    image: "cloudova/cloudova"
#    ports:
#      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example

  adminer:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "soroosh081@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "8000:80"