app: "cloud"

jwt:
  secret: "secret"
mail-service:
  default-email: "sorooshtanzadeh@outlook.com"
spring:
  mail:
    password: springboot
    username: duke
    host: 127.0.0.1
    port: 3025 # default protocol port + 3000 as offset
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
  datasource:
    url: "jdbc:mysql://localhost:3306/cloudova"
    username: "root"
    password: "ee35jeCAMqAgtdC7"
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update